### ISSUE TITLE
LoadImage / LoadTexture not working properly

### ISSUE THREAD

**Issue by akderebur** [M0n7y5/raylib-beef#1]
Hi. Thanks for this project. I was playing around with it a bit, and noticed that methods related to texture and image loading aren't returning proper "Image" and "Texture2D" structs. I mean the methods LoadImage, LoadTexture, LoadImageRaw etc.

Texture loading works fine when loading models with LoadModel, but when trying to load image files directly the returned structs are populated with invalid data. I have checked to see if the structs defined on Beef side match with the Raylib, and they seem fine. Parameters passed to the function looks right too. So I couldn't understand what the problem might be. I hope you might have an idea.

Here is the returned Texture2D data :

![tex_error](https://user-images.githubusercontent.com/13797984/80804652-715a1e80-8bbe-11ea-893a-cd403e55fa47.png)

**Comment by M0n7y5** [comment]
@akderebur It's a bug ... I will fix that

**Comment by M0n7y5** [comment]
@akderebur New version is released. It should be fixed now :) 
Download Here: [https://github.com/M0n7y5/raylib-beef/releases/tag/0.2.1](https://github.com/M0n7y5/raylib-beef/releases/tag/0.2.1)

**Comment by akderebur** [comment]
Works like a charm now. Thanks.
