### ISSUE TITLE
undefined reference to `rCloseWindow'

### ISSUE THREAD

**Issue by joseph-montanez** [M0n7y5/raylib-beef#10]
Both on Windows and Linux has this is undefined using the pre-built Raylib releases:
https://github.com/raysan5/raylib/releases

If change it back to CloseWindow, it works fine.
https://github.com/M0n7y5/raylib-beef/blob/ca09fed55bddc029a72fa3bb91bfeaafc5f2a180/src/Raylib/Core/Windowing.bf#L16

I think this is because you tried to compile this on your own and Raylib has issues with the Windows API when being included.

**Comment by M0n7y5** [comment]
Yeah this is definitely fix for Win API linking. I provided working binaries in release, but only for windows. I am interested in Linux development tho. But i want to use WSL for it, so i need to figure it out few things first. Anyways ... i am gonna push small fix for this ASAP.
