### ISSUE TITLE
Types > Color.bf > ToString function causes error

### ISSUE THREAD

**Issue by afreytes** [M0n7y5/raylib-beef#3]
https://github.com/M0n7y5/raylib-beef/blob/0fe15bcb664ac3e58a1369a75fbe1d518d4ee9be/src/Types/Color.bf#L52

Beef version 0.42.4 raises error on this line: Expected '(' or '['

Downloaded and installed latest release of raylib-beef but the error persists.

**Comment by M0n7y5** [comment]
Oh yeah ... dont use this... i forgot to delete this

**Comment by M0n7y5** [comment]
Fix relesed ...
